<?php require_once __DIR__.'/includes/auth.php'; require_login(); $u=current_user();
function mp_settings(){
  $d=['app_title'=>'EL MASTER PROFE CRM','app_short_title'=>'EL MASTER','app_subtitle'=>'PROFE CRM','title_color'=>'#ffffff','subtitle_color'=>'#ffe05d','brand_color'=>'#3b747b','accent_color'=>'#69d3d1','logo_path'=>'assets/img/icon.svg','favicon_path'=>'assets/img/icon.svg','pwa_icon_path'=>'assets/img/icon.svg','email_logo_path'=>'assets/img/icon.svg','footer_text'=>'© 2026 EL MASTER 10K - Todos los derechos Registrados - Desarrollado por Electrónica Gambino','footer_url'=>'https://electronicagambino.com'];
  try{ db()->exec("CREATE TABLE IF NOT EXISTS app_settings (`key_name` varchar(80) NOT NULL PRIMARY KEY, `value` text NULL, `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"); $rows=db()->query('SELECT key_name,value FROM app_settings')->fetchAll(); foreach($rows as $r){$d[$r['key_name']]=$r['value'];}}catch(Throwable $e){}
  return $d;
}
$cfg=mp_settings(); ?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><link rel="icon" href="<?=htmlspecialchars($cfg['favicon_path'])?>"><title><?=htmlspecialchars($cfg['app_title'])?></title><link rel="manifest" href="manifest.json"><link rel="stylesheet" href="assets/css/app.css"><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script><script src="https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js"></script><script src="https://cdn.jsdelivr.net/npm/jspdf-autotable@3.8.2/dist/jspdf.plugin.autotable.min.js"></script></head><body data-settings='<?=json_encode($cfg,JSON_UNESCAPED_UNICODE)?>' data-user='<?=json_encode($u,JSON_UNESCAPED_UNICODE)?>' data-view='<?=htmlspecialchars($_GET['view'] ?? '')?>' style="--brand: <?=htmlspecialchars($cfg['brand_color'])?>; --brand2: <?=htmlspecialchars($cfg['accent_color'])?>;">
<aside class="sidebar" id="sidebar"><div class="logo" id="collapseBtn"><img id="appLogo" src="<?=htmlspecialchars($cfg['logo_path'])?>"><strong><span class="app-short" style="color:<?=htmlspecialchars($cfg['title_color'])?>"><?=htmlspecialchars($cfg['app_short_title'])?></span><br><span class="app-sub" style="color:<?=htmlspecialchars($cfg['subtitle_color'])?>"><?=htmlspecialchars($cfg['app_subtitle'])?></span></strong></div><nav id="menu"></nav></aside>
<div class="app"><header class="topbar"><div class="desktop-title"><h1 id="desktopPageTitle">Dashboard</h1><p>CRM de socios inversores, referidos, retiros y reparto de ganancias.</p></div><div class="top-actions"><button id="themeBtn" class="iconbtn" title="Tema"></button><button id="fullBtn" class="iconbtn" title="Pantalla completa"></button><div class="notif-wrap"><button id="notifBtn" class="iconbtn bell" title="Notificaciones"></button><div id="notifPreview" class="notif-preview"></div></div><label class="avatar"><img id="profileImg" src="<?=htmlspecialchars($u['profile_photo'] ?: 'assets/img/avatar.svg')?>"><input type="file" id="photoInput" accept="image/*"></label><div class="header-session"><b><?=htmlspecialchars($u['full_name'])?></b><small><?=htmlspecialchars($u['role'])?></small></div><button id="installBtn" class="btn hidden">Instalar</button><button id="logoutBtn" class="btn">Salir</button></div></header><section class="page-heading"><h1 id="pageTitle">Dashboard</h1><p>CRM de socios inversores, referidos, retiros y reparto de ganancias.</p></section><main id="content"></main><footer><div id="footerText"><?=htmlspecialchars($cfg['footer_text'] ?? '© 2026 EL MASTER 10K - Todos los derechos Registrados - Desarrollado por Electrónica Gambino')?><?php if(!empty($cfg['footer_url'])): ?> <a href="<?=htmlspecialchars($cfg['footer_url'])?>" target="_blank">↗</a><?php endif; ?></div><div class="footer-links"><a href="https://creciendofuerte.com" target="_blank">Inicio</a><a href="https://creciendofuerte.com/terminos-y-condiciones" target="_blank">Términos y condiciones</a><a href="https://creciendofuerte.com/politica-de-privacidad" target="_blank">Política de privacidad</a><a href="https://creciendofuerte.com/aml-kyc" target="_blank">AML / KYC</a><a href="https://creciendofuerte.com/contacto" target="_blank">Contacto</a></div></footer></div><button id="filterFloat" class="filter-float hidden" title="Filtros"><?= '' ?></button><div id="waFloat" class="wa-float" title="WhatsApp"></div><nav id="bottomNav" class="mobile-bottom-nav"></nav><div id="moreSheet" class="more-sheet hidden"><div class="more-sheet-card"><div class="more-head"><b>Más módulos</b><button class="rowbtn" id="closeMore">×</button></div><div id="moreLinks"></div></div></div>
<script src="assets/js/app.js"></script></body></html>
